#define STRINGIFY(text) #text

#define VERSION_MAJOR 1
#define VERSION_MINOR 1
#define VERSION_PATCH 0

#define FRAMEWORK_VERSION VERSION_MAJOR##.##VERSION_MINOR##.##VERSION_PATCH
#define FRAMEWORK_VERSION_STRING #FRAMEWORK_VERSION

#define FRAMEWORK_NAME TCS Framework
#define FRAMEWORK_NAME_STRING #FRAMEWORK_NAME
#define FRAMEWORK_NAME_FULL FRAMEWORK_NAME v##FRAMEWORK_VERSION
#define FRAMEWORK_NAME_FULL_STRING STRINGIFY(FRAMEWORK_NAME_FULL)