name: Get changed files
description: Fetches the changed files for the given PR
author: gkovalechyn

inputs:
  pr-id:
    required: true
    description: The PR id
  github-token:
    required: true
    description: The github token

outputs:
  changed-files:
    description: A comma-separated list of changed files
    value: ${{ steps.get-changes.outputs.changed-files }}
  added-files:
    description: A comma-separated list of changed files
    value: ${{ steps.get-changes.outputs.added-files }}
  removed-files:
    description: A comma-separated list of changed files
    value: ${{ steps.get-changes.outputs.removed-files }}
  other-files:
    description: A comma-separated list of changed files
    value: ${{ steps.get-changes.outputs.other-files }}
  all-files:
    description: A comma-separated list of changed files
    value: ${{ steps.get-changes.outputs.all-files }}

runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/action.ps1 -Pr ${{ inputs.pr-id }}
      shell: pwsh
      id: get-changes
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
