name: PR Validation
on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get changed files
        run: |
            branch_sha=`git rev-parse origin/${{ github.base_ref }}`
            changed_files=`git diff --name-only -r $(branch_sha) HEAD | paste -s -d ","`
            echo "Changed files: ${changed_files"}
            echo "changed_files=${changed_files}" >> $GITHUB_OUTPUT

      - name: Common validations
        shell: pwsh
        run: >
          ./.github/scripts/common-validations.ps1
          -ChangedFiles ${{ steps.changed-files.outputs.changed_files }}

      - name: Validate dev branch requirements
        if: github.base_ref == 'dev'
        shell: pwsh
        run: Write-Output 'Succeeded'
        

      - name: Validate master branch requirements
        if: github.base_ref == 'master'
        shell: pwsh
        run: > 
          ./.github/scripts/master-pr-validations.ps1
          -SourceBranch ${{ github.head_ref }}
          -ChangedFiles ${{ steps.changed-files.outputs.changed_files }}
          
