name: PR Validation
on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Validate dev requirements
        if: { github.github.base_ref } == 'dev'
        run: |
          echo 'Succeeded'

      - name: Validate master requirements
        if: { github.github.base_ref } == 'master'
        run: |
          "if [ { github.ref_name } != 'dev' ]; then echo 'Pull requests to the master branch must only be made from the dev branch; exit 1; fi;"
