name: PR Validation
on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Validate dev branch requirements
        if: github.base_ref == 'dev'
        run: |
          echo 'No validations required'

      - name: Validate master branch requirements
        if: github.base_ref == 'master'
        run: |
          "if [ { github.ref_name } != 'dev' ]; then echo 'Pull requests to the master branch must only be made from the dev branch'; exit 1; fi;"
