name: PR Validation
on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35.4.4
        with:
          separator: ","
          since_last_remote_commit: true
          write_output_files: true

      - name: Common validations
        shell: pwsh
        run: >
          ./.github/scripts/common-validations.ps1
          -ChangedFiles ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Validate dev branch requirements
        if: github.base_ref == 'dev'
        shell: pwsh
        run: Write-Output 'Succeeded'
        

      - name: Validate master branch requirements
        if: github.base_ref == 'master'
        shell: pwsh
        run: > 
          ./.github/scripts/master-pr-validations.ps1
          -SourceBranch ${{ github.head_ref }}
          -ChangedFiles ${{ steps.changed-files.outputs.all_changed_files }}
          
