name: PR Validation
on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate dev branch requirements
        if: github.base_ref == 'dev'
        shell: bash
        run: |
          echo 'No validations required'

      - name: Validate master branch requirements
        if: github.base_ref == 'master'
        shell: bash
        run: ./.github/scripts/master-pr-validations.sh
        env:
          SOURCE_BRANCH: ${{ github.head_ref }}