name: Release
on:
  push:
    branches:
      - "master"
      - "dev"
  pull_request:
    branches:
      - master
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get framework version
        uses: ./.github/actions/get-framework-version
        id: get_framework_version

      - name: Generate release body
        uses: ./.github/actions/generate-release-body

      - name: Zip artifacts
        run: |
          zip -r compositions.zip compositions/*
          zip -r framework.zip *.hpp *.ext *.sqf tcs

      - uses: actions/upload-artifact@v3
        if: github.ref_name != 'master'
        with:
          name: outputs
          if-no-files-found: error
          path: |
            framework.zip
            compositions.zip
            releaseBody.md

      - name: Create release
        uses: ncipollo/release-action@v1
        if: github.ref_name == 'master'
        with:
          artifacts: "framework.zip,compositions.zip"
          artifactErrorsFailBuild: true
          bodyFile: "releaseBody.md"
          tag: "v${{ steps.get_framework_version.outputs.version }}"
          token: ${{ secrets.GITHUB_TOKEN }}
